name: Publish editorconfig

on:
  push:
    branches:
      - main
    paths:
      - "packages/editorconfig/.editorconfig"
      - "packages/editorconfig/package.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        working-directory: "packages/editorconfig"
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
