name: Publish editorconfig

on:
  push:
    branches:
      - main
    paths:
      - "packages/editorconfig/.editorconfig"
      - "packages/editorconfig/.package.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./packages/editorconfig/package.json"
