name: Publish eslint-config-fe-eule

on:
  push:
    branches:
      - main
    paths:
      - "packages/eslint-config-fe-eule/.eslintrc.js"
      - "packages/eslint-config-fe-eule/package.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./packages/eslint-config-fe-eule/package.json"
