name: Publish eslint-config-fe-eule

on:
  push:
    branches:
      - main
    paths:
      - "packages/eslint-config-fe-eule/.eslintrc.js"
      - "packages/eslint-config-fe-eule/package.json"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        working-directory: "packages/eslint-config-fe-eule"
        env:
          NODE_AUTH_TOKEN: "${{ secrets.NPM_TOKEN }}"
